apiVersion: v1
kind: Service
metadata:
  name: s0-dpu-svc
  namespace: mubench-dpu
spec:
  selector:
    app: s0-dpu
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # 외부에서 30080으로 접속 시 8080으로 연결
    - name: dpu-bridge
      protocol: TCP
      port: 5005
      targetPort: 5005
      nodePort: 30005  # 외부에서 30005로 접속 시 5005로 연결