apiVersion: v1
kind: Namespace
metadata:
  name: mubench-blocking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s0-dpu-blocking
  namespace: mubench-blocking
  labels:
    app: s0-dpu-blocking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s0-dpu-blocking
  template:
    metadata:
      labels:
        app: s0-dpu-blocking
    spec:
      containers:
      - name: s0-dpu-blocking
        image: mubench-dpu-blocking:latest
        imagePullPolicy: Never
        command: ["python", "CellController-mp_dpu_blocking.py"]
        ports:
        - containerPort: 8080  # Web Server (Metrics etc)
        - containerPort: 5005  # DPU Simulation Bridge
        env:
        - name: APP
          value: "s0"
        - name: ZONE
          value: "us-west-1"
        - name: K8S_APP
          value: "mubench-app"
        - name: PN
          value: "1"
        - name: TN
          value: "4"

---

apiVersion: v1
kind: Service
metadata:
  name: s0-dpu-blocking-svc
  namespace: mubench-blocking
spec:
  selector:
    app: s0-dpu-blocking
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081  # Port 30081 for HTTP to avoid conflict with standard DPU
    - name: dpu-bridge
      protocol: TCP
      port: 5005
      targetPort: 5005
      nodePort: 30006  # Port 30006 for DPU Bridge to avoid conflict with standard DPU