{
 "title": "µBench-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Service delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (app_name) (increase(mub_request_processing_latency_milliseconds_sum{}[2m])) / sum by (app_name) (increase(mub_request_processing_latency_milliseconds_count{}[2m]))",
     "legendFormat": "{{destination_app}}"
    }
   ]
  },
  {
   "title": "Service rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (app_name) (rate(mub_internal_processing_latency_milliseconds_count{}[2m]))",
     "legendFormat": "{{destination_app}}"
    }
   ]
  },
  {
   "title": "Internal service delay ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (app_name) (increase(mub_internal_processing_latency_milliseconds_sum{}[2m])) / sum by (app_name) (increase(mub_internal_processing_latency_milliseconds_count{}[2m]))",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "External service delay ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (app_name) (increase(mub_external_processing_latency_milliseconds_sum{}[2m])) / sum by (app_name) (increase(mub_external_processing_latency_milliseconds_count{}[2m]))",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "CPU x service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (container) (increase(container_cpu_usage_seconds_total{container=~\"s.*[0-9].*\",service=\"prometheus-kube-prometheus-kubelet\"}[2m])/120)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory x service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (container) (sum_over_time(container_memory_usage_bytes{pod=~\"s[0-9].*\",service=\"prometheus-kube-prometheus-kubelet\"}[2m]) / count_over_time(container_memory_usage_bytes{pod=~\"s[0-9].*\",service=\"prometheus-kube-prometheus-kubelet\"}[2m])) / 1e6",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU usage / CPU requested x Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (container) (increase(container_cpu_usage_seconds_total{container=~\"s.*[0-9].*\", image!~\"k8s.gcr.io/pause:3.5\",service=\"prometheus-kube-prometheus-kubelet\"}[2m])) / (120 * sum by (container) (kube_pod_container_resource_requests{container=~\"s[0-9].*\"}))",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}