FROM python:3.9-slim

WORKDIR /app

# Dependencies
RUN pip install --no-cache-dir requests

# Copy dpumesh library
COPY ServiceCell/dpumesh/ /app/dpumesh/

# Environment
ENV PYTHONUNBUFFERED=1

# Run DMA Manager
CMD ["python", "-m", "dpumesh.dpa_daemon"]